version: "3"

volumes:
  postgres: {}
  caddy_data:
  caddy_config:
  
services:  
  postgres:
    image: "postgres:12-alpine"
    env_file:
      - ./.envs/.postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    networks: 
      - bridge_network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: gin-backend:latest
    container_name: dishes-backend
    command: /dishes-admin/dishes-admin web -c /dishes-admin/configs/config.toml -m /dishes-admin/configs/model.conf --menu /dishes-admin/configs/menu.yaml
    depends_on:
      - postgres
    expose:
      - 10088
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    networks: 
      - bridge_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    image: gin-frontend:latest
    container_name: dishes-frontend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks: 
      - bridge_network

networks:
  bridge_network:
    driver: bridge
