---
# 菜单配置初始化(服务启动时会进行数据检查，如果存在则不再初始化)
- name: 用户管理
  icon: user
  router: "/system/user"
  sequence: 9
  actions:
    - code: add
      name: 新增
      resources:
        - method: GET
          path: "/api/v1/roles.select"
        - method: POST
          path: "/api/v1/users"
    - code: edit
      name: 编辑
      resources:
        - method: GET
          path: "/api/v1/roles.select"
        - method: GET
          path: "/api/v1/users/:id"
        - method: PUT
          path: "/api/v1/users/:id"
    - code: del
      name: 删除
      resources:
        - method: DELETE
          path: "/api/v1/users/:id"
    - code: query
      name: 查询
      resources:
        - method: GET
          path: "/api/v1/users"
    - code: disable
      name: 禁用
      resources:
        - method: PATCH
          path: "/api/v1/users/:id/disable"
    - code: enable
      name: 启用
      resources:
        - method: PATCH
          path: "/api/v1/users/:id/enable"

- name: 示例
  icon: table
  router: "/system/demo"
  sequence: 8
  actions:
    - code: add
      name: 新增
      resources:
        - method: POST
          path: "/api/v1/demos"
    - code: edit
      name: 编辑
      resources:
        - method: GET
          path: "/api/v1/demos/:id"
        - method: PUT
          path: "/api/v1/demos/:id"
    - code: del
      name: 删除
      resources:
        - method: DELETE
          path: "/api/v1/demos/:id"
    - code: query
      name: 查询
      resources:
        - method: GET
          path: "/api/v1/demos"

- name: 产品
  icon: table
  router: "/system/products"
  sequence: 7
  actions:
    - code: add
      name: 新增
      resources:
        - method: POST
          path: "/api/v1/products"
    - code: edit
      name: 编辑
      resources:
        - method: GET
          path: "/api/v1/products/:id"
        - method: PUT
          path: "/api/v1/products/:id"
    - code: del
      name: 删除
      resources:
        - method: DELETE
          path: "/api/v1/products/:id"
    - code: query
      name: 查询
      resources:
        - method: GET
          path: "/api/v1/products"

- name: 固件
  icon: table
  router: "/system/firmwares"
  sequence: 7
  actions:
    - code: add
      name: 新增
      resources:
        - method: POST
          path: "/api/v1/firmwares"
    - code: edit
      name: 编辑
      resources:
        - method: GET
          path: "/api/v1/firmwares/:id"
        - method: PUT
          path: "/api/v1/firmwares/:id"
    - code: del
      name: 删除
      resources:
        - method: DELETE
          path: "/api/v1/firmwares/:id"
    - code: query
      name: 查询
      resources:
        - method: GET
          path: "/api/v1/firmwares"

- name: 设备
  icon: table
  router: "/system/devices"
  sequence: 6
  actions:
    - code: add
      name: 新增
      resources:
        - method: POST
          path: "/api/v1/devices"
    - code: edit
      name: 编辑
      resources:
        - method: GET
          path: "/api/v1/devices/:id"
        - method: PUT
          path: "/api/v1/devices/:id"
    - code: del
      name: 删除
      resources:
        - method: DELETE
          path: "/api/v1/devices/:id"
    - code: query
      name: 查询
      resources:
        - method: GET
          path: "/api/v1/devices"

- name: 更新
  icon: table
  router: "/system/upgrades"
  sequence: 6
  actions:
    - code: add
      name: 新增
      resources:
        - method: POST
          path: "/api/v1/upgrades"
    - code: edit
      name: 编辑
      resources:
        - method: GET
          path: "/api/v1/upgrades/:id"
        - method: PUT
          path: "/api/v1/upgrades/:id"
    - code: del
      name: 删除
      resources:
        - method: DELETE
          path: "/api/v1/upgrades/:id"
    - code: query
      name: 查询
      resources:
        - method: GET
          path: "/api/v1/upgrades"